public class NameGenerator
{
    public static string[] Names =
    {
        "Aspect",
        "Kraken",
        "Bender",
        "Lynch",
        "Big Papa",
        "Mad Dog",
        "Bowser",
        "O'Doyle",
        "Bruise",
        "Psycho",
        "Cannon",
        "Ranger",
        "Clink",
        "Ratchet",
        "Cobra",
        "Reaper",
        "Colt",
        "Rigs",
        "Crank",
        "Ripley",
        "Creep",
        "Roadkill",
        "Daemon",
        "Ronin",
        "Decay",
        "Rubble",
        "Diablo",
        "Sasquatch",
        "Doom",
        "Scar",
        "Dracula",
        "Shiver",
        "Dragon",
        "Skinner",
        "Fender",
        "Skull Crusher",
        "Fester",
        "Slasher",
        "Fisheye",
        "Steelshot",
        "Flack",
        "Surge",
        "Gargoyle",
        "Sythe",
        "Grave",
        "Trip",
        "Gunner",
        "Trooper",
        "Hash",
        "Tweek",
        "Hashtag",
        "Vein",
        "Indominus",
        "Void",
        "Ironclad",
        "Wardon",
        "Killer",
        "Wraith",
        "Knuckles",
        "Zero",
        "Steel",
        "Kevlar",
        "Lightning",
        "Tito",
        "Bullet-Proof",
        "Fire-Bred",
        "Titanium",
        "Hurricane",
        "Ironsides",
        "Iron-Cut",
        "Tempest",
        "Iron Heart",
        "Steel Forge",
        "Pursuit",
        "Steel Foil",
        "Sick Rebellion",
        "Upsurge",
        "Uprising",
        "Overthrow",
        "Breaker",
        "Sabotage",
        "Dissent",
        "Subversion",
        "Rebellion",
        "Insurgent",
        "Accidental Genius",
        "Acid Gosling",
        "Admiral Tot",
        "AgentHercules",
        "Airport Hobo",
        "Alley Frog",
        "Alpha",
        "AlphaReturns",
        "Angel",
        "AngelsCreed",
        "Arsenic Coo",
        "Baby Brown",
        "Back Bett",
        "Bad Bunny",
        "Bearded Angler",
        "Beetle King",
        "Betty Cricket",
    };

    public static string GetName()
    {
        return Names[UnityEngine.Random.Range(0, Names.Length)].Split(' ')[0];
    }
}